language: node_js
node_js:
  # latest in each series
  - "4"
# Need a C++ compiler
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
before_script:
  - npm install -g gulp
  - cp sampleGlobalConstants_dev.js GlobalConstants_dev.js
script:
  - gulp buildDev
notifications:
  # no emails please
  email: false