language: node_js
node_js:
  # latest in each series
  - "4"
# Need a C++ compiler
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
      repo_token: 46c452ebeacc1e58225184c9d3275142f7579b3212e301e42a9625a0987e556d
env:
  - CXX=g++-4.8
before_script:
  - npm install -g gulp
  - cp sampleGlobalConstants_dev.js GlobalConstants_dev.js
script:
  - gulp buildDev
  - gulp lint
  - npm test
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
notifications:
  email: false